using System;
using AutoPoco.Engine;

namespace AutoPoco.DataSources
{
    public class CitySource : DatasourceBase<String>
    {
        private static readonly Random _random = new Random();

        public override string Next(IGenerationContext context)
        {
            return _cities[_random.Next(0, _cities.Length)];
        }

        private static readonly string[] _cities =
        {
            "New York",
            "Los Angeles",
            "Chicago",
            "Houston",
            "Philadelphia",
            "Phoenix",
            "San Diego",
            "San Antonio",
            "Dallas",
            "Detroit",
            "San Jose",
            "Indianapolis",
            "Jacksonville",
            "San Francisco",
            "Columbus",
            "Austin",
            "Memphis",
            "Baltimore",
            "Charlotte",
            "Fort Worth",
            "Boston",
            "Milwaukee",
            "El Paso",
            "Washington",
            "Nashville-Davidson",
            "Seattle",
            "Denver",
            "Las Vegas",
            "Portland",
            "Oklahoma City",
            "Tucson",
            "Albuquerque",
            "Atlanta",
            "Long Beach",
            "Kansas City",
            "Fresno",
            "New Orleans",
            "Cleveland",
            "Sacramento",
            "Mesa",
            "Virginia Beach",
            "Omaha",
            "Colorado Springs",
            "Oakland",
            "Miami",
            "Tulsa",
            "Minneapolis",
            "Honolulu",
            "Arlington",
            "Wichita",
            "St. Louis",
            "Raleigh",
            "Santa Ana",
            "Cincinnati",
            "Anaheim",
            "Tampa",
            "Toledo",
            "Pittsburgh",
            "Aurora",
            "Bakersfield",
            "Riverside",
            "Stockton",
            "Corpus Christi",
            "Lexington-Fayette",
            "Buffalo",
            "St. Paul",
            "Anchorage",
            "Newark",
            "Plano",
            "Fort Wayne",
            "St. Petersburg",
            "Glendale",
            "Lincoln",
            "Norfolk",
            "Jersey City",
            "Greensboro",
            "Chandler",
            "Birmingham",
            "Henderson",
            "Scottsdale",
            "North Hempstead",
            "Madison",
            "Hialeah",
            "Baton Rouge",
            "Chesapeake",
            "Orlando",
            "Lubbock",
            "Garland",
            "Akron",
            "Rochester",
            "Chula Vista",
            "Reno",
            "Laredo",
            "Durham",
            "Modesto",
            "Huntington",
            "Montgomery",
            "Boise",
            "Arlington",
            "San Bernardino"
        };
    }

    public class StateSource : DatasourceBase<String>
    {
        private static readonly Random _random = new Random();

        public override string Next(IGenerationContext context)
        {
            return _states[_random.Next(0, _states.Length)];
        }

        private static readonly string[] _states =
        {
            "AL",
            "AK",
            "AS",
            "AZ",
            "AR",
            "CA",
            "CO",
            "CT",
            "DE",
            "DC",
            "FM",
            "FL",
            "GA",
            "GU",
            "HI",
            "ID",
            "IL",
            "IN",
            "IA",
            "KS",
            "KY",
            "LA",
            "ME",
            "MH",
            "MD",
            "MA",
            "MI",
            "MN",
            "MS",
            "MO",
            "MT",
            "NE",
            "NV",
            "NH",
            "NJ",
            "NM",
            "NY",
            "NC",
            "ND",
            "MP",
            "OH",
            "OK",
            "OR",
            "PW",
            "PA",
            "PR",
            "RI",
            "SC",
            "SD",
            "TN",
            "TX",
            "UT",
            "VT",
            "VI",
            "VA",
            "WA",
            "WV",
            "WI",
            "WY"
        };
    }

}